# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-31 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20181231_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.TextField(default='产品详情', verbose_name='产品描述'),
        ),
    ]
