# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-31 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20181231_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='产品名称')),
                ('image', models.ImageField(upload_to='static/images', verbose_name='产品图片')),
                ('detail', models.TextField(default='产品详情', verbose_name='产品描述')),
                ('status', models.BooleanField(default=True, verbose_name='产品状态')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.Product')),
            ],
        ),
    ]
