# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-31 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_detailpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Banner')),
                ('image', models.ImageField(upload_to='static/images', verbose_name='轮播图')),
                ('detail', models.TextField(default='产品详情', verbose_name='产品描述')),
                ('status', models.BooleanField(default=True, verbose_name='产品状态')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.Category')),
            ],
        ),
        migrations.AlterField(
            model_name='detailpage',
            name='detail',
            field=models.TextField(default='产品详情', verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='detailpage',
            name='image',
            field=models.ImageField(upload_to='static/images', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='detailpage',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名称'),
        ),
    ]
